<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <MauiAsset Include="Resources/**" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Models/**/*.cs" Link="Shared\Models\%(Filename)%(Extension)" />
    <Compile Include="PrayerCalculations/**/*.cs" Link="Shared\PrayerCalculations\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
